### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/reimagined-fiesta#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'Unwatch' button and selecting either the 'Not watching' or 'Ignoring' option.

**Comment by isralduke** [comment]
I see it’s a Jekyll site.

**Comment by andreybar2** [comment]
I am here

**Comment by Bragas2** [comment]
Being added as a collaborator

**Comment by jtcoward** [comment]
Hello!

**Comment by parkerbxyz** [comment]
This is **bold** text. And this isn't.

- This is an [unordered](#) list
- This is still part of the same list

1. This is an ordered list
1. This is the new number 2
1. This is number 2
1. This is number 3


- [ ] This is a checklist
- [x] This task is done!

**Comment by cdcavell** [comment]
@parkerbxyz, @cdcavell is Chris Cavell 😄

**Comment by dylanmlabat** [comment]
_comment_

**Comment by blakecapello** [comment]
blakecapello

**Comment by tkoubre** [comment]
Greetings! Tandra

**Comment by alishaba909** [comment]
I'm here also.

**Comment by jenlyn-higgins** [comment]
**Hooray** it _works_! 😺 

- [ ] I

- [ ] Was

- [ ] Here

**Comment by frogpad7** [comment]
This is Charles here -> @frogpad7

**Comment by isralduke** [comment]
```html
    <p>i am a sentence.</p>
```

**Comment by SaveFarris** [comment]
This is not a comment.

**Comment by hephelump37** [comment]
this is Eric Davis

`public async Task<IActionResult<VoidBot>>(){
return new VoidBot();
}`

**Comment by duc-la-git** [comment]
this is duc

**Comment by P00159894** [comment]
I'm here

**Comment by P00159894** [comment]
```C#
string  t = "I  am WFH"
```
```html
<p>I am WFH</p>

**Comment by parkerbxyz** [comment]
Thanks, everyone!
